### PR TITLE
Implement triangle shape

### PR DESCRIPTION
**Pull request by Droggelbecher**
Implement arbitrary triangles which can also be useful for painting filled quads or more complex shapes.

### CODE REVIEW

**Comment by james-j-obrien** [comment]
Very nice, will look to merge this for the next release.

**Comment by musjj** [comment]
Does it make sense to have a separate shape for a triangle? Wouldn't it be redundant once arbitrary polygons are supported?

**Comment by Droggelbecher** [comment]
I leave that decision up to the package maintainers, for me it was just the less intimidating starting point.

I might be tempted to do polygons some time in the coming days as well, in essence it shouldn't be much more work than understanding https://www.shadertoy.com/view/wdBXRW and translating it to WGSL, right?

**Comment by james-j-obrien** [comment]
The difference between the triangle shader here and the general polygon shader is that the triangle shader doesn't loop so will be much more performant than the polygon shader even when both are drawing triangles. I think it makes senses to have both so you can draw bordered/rounded triangles without paying for the arbitrary polygon sdf calculation.

And yes, adding most shapes to the library is just a matter of translating the relevant shader toy examples that you can usually find haha.

**Comment by Droggelbecher** [comment]
On closer look seems I do struggle a bit with how to get the points data to the shader. My understanding of the whole bevy render pipeline so far was superficial at best and seems you do some special things here (eg seems you don't use uniforms for some reason?).

If someone could help me out with a code sketch on what you think would be the correct way to pass variable-sized data to the shader in this repo, I'd gladly take it from there

**Comment by james-j-obrien** [comment]
Each polygon has a set of points with undefined length that you need to be able to access in the shader. What you would do first is push all the points for every polygon into one big points buffer, recording the start and end index in the shape's data. Iterating through the points would then look something like this:
```wgsl
for (var i = shape.start; i < shape.end; i++) {
    var point = points[i];
    ...
}
```
All that's left is making the buffer available to the gpu in the shader. Bevy has recently merged an abstraction for buffers: 
https://github.com/bevyengine/bevy/pull/8204
It uses a storage buffer on desktop but a series of uniform buffers on webgl2 since it doesn't support storage buffers. It's not in 0.11 but will be available in 0.12 which should release relatively soon. I have a branch supporting 0.12 here: 
https://github.com/james-j-obrien/bevy_vector_shapes/tree/bevy-0.12 
The branch uses that abstraction for all shape data so acts as a much better starting point for poly* shapes and contains all the code that you would need to create a buffer and fill it with data. If you wanted to you could create a PR to that branch and I will review and merge it before releasing for 0.12.

**Pull request merged**
